<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Object Oriented Programming
              
</p>
</div>

Data Science Cohort Live NYC Feb 2022
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

#### Objected Oriented Programming

- We've actually been using this without realizing it.


#### Examples

- results object in statsmodels OLS fit
- requests object or BeautifulSoup objects in web scraping
- sklearn LinearRegression models
- fig and ax objects in Matplotlib

#### Object Oriented Program in a Nutshell

<center><img src = "Images/pikachu.png" width = 800 /></center>

- Class: Pokemon
- object instance of Pokemon class

- Attributes = Fields. Properties of object instance.
- Methods: an action. Can change state of object instance.

<center><img src = "Images/pikachu.png" width = 800 /></center>

-  **Class**: general class of similar objects
- Want common attributes/methods for each instantiated object

**Pokemon is general class. Pikachu is an object of class Pokemon.**

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Fields/Attributes**:
- objects of same class share same attributes
- each attribute takes on different values for different instantiations.
    
e.g., Name, Type, Health attributes common to all pokemons


But Pikachu and Bulbasaur:
- different values of attributes.

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Methods**:
- Objects in given Class can execute common set of functions
- Functions can change internal state of object
    - i.e. change attributes: .evolve() can change health, name, etc.

#### Creating a class in Python

Create simple class using class constructor and initialization:

In [83]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

the __init__ method is a special function:

- the first argument is always: *self*
- *self* refers to specific instance of class. 
- the other arguments: used in initializing instance.


In [84]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

#### Let's see this in action 

Create an instance of a Pokemon:
- Create and instantiate a Pikachu.

In [85]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

Let's check out some of the attributes

In [86]:
pikachu.name

'Pikachu'

In [87]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points

- So far the class object is like a grouping of variables (like a dict). 
- Adding methods give class objects a richer structure

#### Methods

- Create functions that:
    - return object state
    - update object state (i.e. change internal attributes)
    - do it based on information external to object.


In [97]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
    
    def get_state(self):
        
        state_dict = {'name': self.name, 'level': self.level, 'life': self.life,
                     'attack': self.attack_power, 'defense': self.defense_points}
        return state_dict
        
    def evolve(self, evolved_name):
        #Change Pokemon name to given evolved name state
        self.name = evolved_name
        
        #level up the stats
        self.level += 1
        self.life += 30
        self.attack_power += 4
        self.defense_points += 3

In [98]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [100]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

<img src = "Images/evolution_phases.jpeg" width = 700 />

In [95]:
pikachu.evolve('Raichu')

In [401]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

Let's have fun with another class:
- Create a koala class with each instance a koala that eats bunches of eucalyptus and poops.
- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

<center><img src = "Images/gastro.jpg" width = 1000/></center>

Your data science instructor really doesn't get this objected oriented programming stuff! Help him out.

In [ ]:
class Koala:
    
    # first need to initialize. 
    #define relevant variables.
    def ??(??, belly_weight, name, alive):
        
    # create eat_eucalyptus() method
    def eat_eucalyptus(self, num_bunches = 1):
        ???

    # create poop() method
    ???
    
    


- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

Now for why all this is relevant to our work in data science.

In [139]:
class Standardizer:
    
    def __init(self):
        self.mean_series = None
        self.stdev_series = None
    
    def fit(self, data):
        self.mean_series = data.mean()
        self.stdev_series = data.std(ddof = 1)
        
    def transform(self, X):
        X_standard = (X - self.mean_series)/self.stdev_series 
        return X_standard
    
    def fit_transform(self, X):
        #fit with X
        self.fit(X)
        #apply transformation to X
        transformed = self.transform(X)
        return transformed      

In [314]:
heart_df = pd.read_csv('Data/heart.csv', usecols = ['age', 'chol', 'thalach', 'target'])
heart_df.head()

age  chol  thalach  target
0   63   233      150       1
1   37   250      187       1
2   41   204      172       1
3   56   236      178       1
4   57   354      163       1

Split into train and test sets.

In [315]:
from sklearn.model_selection import train_test_split
X = heart_df.drop(columns = ['target'])
y = heart_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Let's use our standardizer class! 
- Instantiate transformer object.
- Fit our standardizer object to the training set.

In [316]:
sd = Standardizer()

In [317]:
sd.mean_series

AttributeError: 'Standardizer' object has no attribute 'mean_series'

In [318]:
sd.std_series

AttributeError: 'Standardizer' object has no attribute 'std_series'

Fit the transformer.

In [319]:
sd.fit(X_train)

In [320]:
sd.mean_series

age         54.595041
chol       246.458678
thalach    149.545455
dtype: float64

In [321]:
sd.stdev_series

age         9.018265
chol       53.291187
thalach    22.149436
dtype: float64

Means and standard deviations for each column:
- extracted (fit) from training set.
- use these parameters to transform both train and test

#### Transform train set

In [322]:
X_train_standard = sd.transform(X_train)
X_train_standard.head()

age      chol   thalach
63  -1.507501 -0.815495 -0.792140
215 -1.285729  1.774052 -0.611549
172  0.377562  0.704456  0.472001
23   0.710221 -0.064901 -0.566401
289  0.044904 -0.777965 -0.882436

In [323]:
X_train_standard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242 entries, 63 to 222
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      242 non-null    float64
 1   chol     242 non-null    float64
 2   thalach  242 non-null    float64
dtypes: float64(3)
memory usage: 7.6 KB


In [324]:
X_train_standard.mean()

age       -4.165630e-16
chol      -1.174451e-16
thalach    5.697921e-16
dtype: float64

#### Transform test set
- Use fitted parameters to transform test set.

In [325]:
X_test_standard = sd.transform(X_test)
X_test_standard.head()

age      chol   thalach
267 -0.620412 -1.828795 -1.063027
51   1.264651  1.042223  0.065670
5    0.266676 -1.021908 -0.069774
300  1.486423 -1.003143 -0.385809
276  0.377562 -0.534022 -2.011133

In [326]:
X_test_standard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 61 entries, 267 to 95
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      61 non-null     float64
 1   chol     61 non-null     float64
 2   thalach  61 non-null     float64
dtypes: float64(3)
memory usage: 1.9 KB


Scikit-learn transformers are instances of class objects.

In [327]:
from sklearn.preprocessing import StandardScaler
sklearn_sd = StandardScaler()

X_train_sklearn = sklearn_sd.fit_transform(X_train)

In [328]:
sklearn_sd.mean_

array([ 54.59504132, 246.45867769, 149.54545455])

In [329]:
sklearn_sd.scale_

array([ 8.99961295, 53.18096685, 22.10362522])

Looking at the desciptive statistics of the transformed $X_{train}$:

In [330]:
print(X_train_sklearn.mean(axis = 0))

[-3.63345717e-16 -1.17445080e-16  5.72544766e-16]


In [331]:
print(X_train_sklearn.std(axis = 0))

[1. 1. 1.]


Yeah, its doing the same thing as our hard-coded class.

#### Models in scikit-learn
- Also classes with different methods.
- .fit()
- .predict()
- .fit_predict()
- .score(X,y)

LinearRegression() was an example.

In [405]:
from numpy import linalg # linear algebra subpackage
import numpy as np

Implementing custom OLS linear regression class:
- sklearn model doing similar things under hood of
    - .fit(X,y) method
    - .predict(X) method
    - etc.

In [391]:
class CustomLinearRegression:
    
    def __init__(self):
        self.intercept = None
        self.coeff = None
        
    def fit(self, X_in, y):
        
        #create a column of 1s for offset fitting
        bias_col = np.ones(X_in.shape[0]).reshape(-1,1) 
    
        #augmented data matrix with column of ones
        X = np.hstack((bias_col, X_in))
        
        # weights: result of least squares minimization
        w = linalg.inv(X.T@X)@(X.T@y)
        # its a formula
        
        self.intercept = w[0]
        self.coeff = w[1::]
        
    # same as y = beta_0 + beta_1*x_1 + beta_2*x_2 + ... + beta_n*x_n
    #just more compact. we'll see later.
    def predict(self, X):
        y_pred = X@self.coeff + self.intercept
        return y_pred
    

Create instances of our custom model and scikit-learn linear regression model

In [392]:
from sklearn.linear_model import LinearRegression
clr = CustomLinearRegression()
sklearn_lr = LinearRegression()

Scikit-learn linear regression .fit() method:
- find weights/model parameters

In [393]:
clr.fit(X_train, y_train)
sklearn_lr.fit(X_train, y_train)

LinearRegression()

In [394]:
clr.coeff

array([-0.0043265 , -0.00078318,  0.00856983])

In [395]:
sklearn_lr.coef_

array([-0.0043265 , -0.00078318,  0.00856983])


Under the hood, sklearn model is:

Class object with model parameters as attributes.

- .fit(X,y) method uses formula or algorithm to find model parameters (weights)
- used X, y as training data

- .predict(X) 
    - learned parameters + X into model
    - get prediction

In [399]:
clr.predict(X_test)[0:5]

267    0.427680
51     0.448548
5      0.547927
300    0.439564
276    0.154735
dtype: float64

In [404]:
sklearn_lr.predict(X_test)[0:5]

array([0.42767977, 0.44854841, 0.54792729, 0.43956384, 0.15473537])

We showed:
- Clearly how sklearn works under the hood via class objects   
- But not integrated into the scikit-learn library
    


Next: 
- Learn about parent/child classes
- Inheritance and class hierarchy
- Integrate our models/transformers into scikit-learn class hierarchy.