<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Class inheritance / custom classes in scikit-learn 
              
</p>
</div>

Data Science Cohort Live NYC Feb 2022
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

####  Hierarchical class structures and inheritance
<img src = "Images/class-inheritance.png" width = 600/>

Car and motorcycle are examples of vehicle:
- Vehicle: **parent class**
- Car/Motorcycle: **children**

Children class:
- share methods/attributes from parent
- will also have specific additional methods/attributes

#### Reason to do this
- Tremendous reduction in code
- Specific custom class: can inherit routines/variabes/functionality from parents.
- Custom class: adapt to specific use case and plug into general framework.

Let's see some of this in action in Python:
- Define parent class: 

In [77]:
class Vehicle:
    
    def __init__(self, color = 'Gray'):
        self.started = False
        self.color = color
        self.speed = 0
        
    def start(self):
        self.started = True
        
    def turn_off(self):
        if self.speed == 0:
            self.started = False
        else:
            print('User is idiot. Request denied.')
    
    def increase_speed(self, delta):
        if self.started == True:
            self.speed += delta
        else:
            print('Vehicle is off...')
    
    def slow_down(self, delta):
        calc = self.speed - delta
        if (self.started == True) & (calc >= 0):
            self.speed = calc
        else:
            pass
                
    def stop(self):
        self.speed = 0

In [78]:
veh_inst = Vehicle()

In [79]:
veh_inst.start() 

In [80]:
veh_inst.started

True

In [81]:
veh_inst.speed

0

In [82]:
veh_inst.increase_speed(10)

In [83]:
veh_inst.speed

10

In [84]:
veh_inst.color

'Gray'

Parent has general functions and attributes that we want to reuse for specific types of vehicles:
- Define child class Car specifying the parent class as Vehicle.
- Cars can be started, turned off, sped up/ slowed down (methods of Vehicle)
- Car has a speed and color (attributes of Vehicle)


Color is special attribute here:
- Is argument of parent constructor/initializer

In [9]:
class Vehicle:
    
    def __init__(self, color = 'Gray'):
        self.started = False
        self.color = color
        self.speed = 0
        
    def start(self):
        self.started = True
        
    def turn_off(self):
        if self.speed == 0:
            self.started = False
        else:
            print('User is idiot. Request denied.')
    
    def increase_speed(self, delta):
        if self.started == True:
            self.speed += delta
        else:
            print('Vehicle is off...')
    
    def slow_down(self, delta):
        calc = self.speed - delta
        if (self.started == True) & (calc >= 0):
            self.speed = calc
        else:
            pass
                
    def stop(self):
        self.speed = 0

Want as argument of child class initializer:

- want to set this parent attribute from child class constructor
- E.g. Car(color = 'blue'):
    - creates Car instance
    - inherited attribute color to blue.

Want: child constructor taking parameters of parent constructor as arguments.

**Within child initializer**
- Need to call initializer of parent class.
- This allows parent and child to share attributes
- Relevant child initializer arguments passed to parent initializer



In [86]:
class Car(Vehicle):
    
    def __init__(self, color):
        self.trunk_open = False
        Vehicle.__init__(self, color)
    def open_trunk(self):
        if self.trunk_open == False:
            self.trunk_open = True
        else:
            print('Trunk already open')
    def close_trunk(self):
        if self.trunk_open == True:
            self.trunk_open = False
        else:
            print('Trunk is already closed.')

- parent.__init__(self, arguments)
- super().__init__(arguments)

In [87]:
# passed to parent constructor
my_moms_car = Car('Blue')

In [88]:
# attribute inherited from Vehicle
my_moms_car.color

'Blue'

In [89]:
# method in Car class (child)
my_moms_car.open_trunk()

In [90]:
# attribute of Car (child)
my_moms_car.trunk_open

True

In [91]:
# method/attribute inherited from parent (Vehicle)

my_moms_car.start()
my_moms_car.started
# Note: "started" was attribute not passed into child constructor/super() method
# not a parameter of child/parent class initializer

True

To reiterate

In [16]:
class Car(Vehicle):
    
    def __init__(self, color):
        self.trunk_open = False
        super().__init__(color)
    def open_trunk(self):
        if self.trunk_open == False:
            self.trunk_open = True
        else:
            print('Trunk already open')
    def close_trunk(self):
        if self.trunk_open == True:
            self.trunk_open = False
        else:
            print('Trunk is already closed.')

Car is child of Vehicle:
- clearly inherits methods/attributes from Vehicle
- Also has own subroutines/attributes (trunk_open,etc.)

- color is argument of Vehicle constructor
- specifying in __init__ method of child passes it to parent through:
    - super().__init__(color)
    - parent.__init__(self, color)

#### Multiple Inheritance

#### Child class can have multiple parents
- Inherits methods/routines from multiple parents

<img src = "Images/multipleinh.png" width = 600 />

In [92]:
class Property:
    
    def __init__(self, owner_name = None, years_owned = None, assessed_value = None):
        
        self.owner_name = owner_name
        self.years_owned = years_owned 
        self.assessed_value = assessed_value
        
    def change_owner(self, name):
        self.owner_name = name
        self.years_owned = 0
        
    def revalue_asset(self, new_value):
        self.assessed_value = new_value

In [93]:
class Car(Property, Vehicle):
    
    def __init__(self, color, owner_name = None, years_owned = None, assessed_value = None):
        Property.__init__(self, owner_name, years_owned, assessed_value)
        Vehicle.__init__(self, color)
        
        self.trunk_open = False
        
    def open_trunk(self):
        if self.trunk_open == False:
            self.trunk_open = True
        else:
            print('Trunk already open')
    def close_trunk(self):
        if self.trunk_open == True:
            self.trunk_open = False
        else:
            print('Trunk is already closed.')
        
        

Car now inherits methods/attributes from both Property and Vehicle

In [95]:
Karan_Honda = Car(color = 'Red',
        owner_name = 'Karan Kurdia',
        assessed_value = 6000)

In [96]:
#from Property Class
print(Karan_Honda.owner_name)
print(Karan_Honda.assessed_value)

Karan Kurdia
6000


In [98]:
Karan_Honda.revalue_asset(3000)

In [99]:
Karan_Honda.assessed_value

3000

In [100]:
# from vehicle
Karan_Honda.color

'Red'

In [101]:
#from Car class
Karan_Honda.trunk_open

False

In [102]:
# from Vehicle class
Karan_Honda.start()
Karan_Honda.started

True

The why of all this:

The unifying principle here is **modularity**.

- Enables us to use frameworks that already exist.
- Input custom functionality as little box into larger framework.

**Enables building more complex systems quickly.**

<center><img src = "Images/modular_design.png" /></center>

**Scikit-learn (your workhorse Machine learning package)**: built with many of these design principles in mind.

Allows you to:

- Include transformations/modeling into a bus modular flow.
- **Scikit-learn pipeline**

- Try different models out on your data in plug and play fashion
- Test performance and get best result.
- **Model tuning and cross-validation**

- Custom models and transformers: classes
- Inheritance allows us to plug/play into Scikit-learn.

First necessary parent class for any custom model:

In [103]:
from sklearn.base import BaseEstimator 

Enables the getting and setting of **user-controlled variables** for a model
- Not parameters fit by the model.
- Rather external levers for model: known as **hyperparameters**.

Now: 
- *hyperparameters* accessible to other sklearn classes.
- Useful: model tuning, etc.

Second parent necessary for any transformer:

In [104]:
from sklearn.base import TransformerMixin

Now if you write:
- .fit()
- .transform()

- Enables .fit_transform() automatically

**More importantly**

- Sklearn recognizes as transformer.
- Enables plugging into sklearn Transformer framework.

#### Make our own custom scikit-learn transformer

Some scenarios:
- Want to define custom transformation to data columns
- Want to apply different transformations to different subsets of columns

Create new _transformer_:

- If the value is **positive**, scale the value by the **largest value** in that column
- If the value is **negative**, change it to $0$

In [105]:
class SpecialTransformer(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.max_ = None
        BaseEstimator.__init__(self)
        TransformerMixin.__init__(self)
    
    def fit(self, X, y=None):
        self.max_ = np.max(X,axis=0) 
        return self
    
    def transform(self, X):
        X_copy = np.copy(X)
        X_copy[X_copy < 0] = 0
        return X_copy / self.max_

In [106]:
## Let's use some test data
# Note each column is a feature, each row a data point
import numpy as np
X = np.array([
    [-4, 400, 40],
    [10, -100, 1],
    [6, -800, 700],
    [2, 0, 400],
    [8, 200, 1000]
])

X.shape

(5, 3)

Let's use our transformer on the entire array:
- First initialize instance.
- Fit to array

In [107]:
trans_instance = SpecialTransformer()
trans_instance.fit(X)

SpecialTransformer()

In [108]:
trans_instance.max_

array([  10,  400, 1000])

Using these fit parameters: 
- Can apply transformation to any data with 3 columns.
- Let's just apply to our X for now.

In [64]:
trans_instance.transform(X)

array([[0.   , 1.   , 0.04 ],
       [1.   , 0.   , 0.001],
       [0.6  , 0.   , 0.7  ],
       [0.2  , 0.   , 0.4  ],
       [0.8  , 0.5  , 1.   ]])

In [65]:
class SpecialTransformer(BaseEstimator, TransformerMixin):
    
    def __init__(self):
        self.max_ = None
        BaseEstimator.__init__(self)
        TransformerMixin.__init__(self)
    
    def fit(self, X, y=None):
        self.max_ = np.max(X,axis=0) 
        return self
    
    def transform(self, X):
        X_copy = np.copy(X)
        X_copy[X_copy < 0] = 0
        return X_copy / self.max_

Specifying parent TransformerMixin:
- enabled parent method .fit_transform

In [109]:
trans_instance.fit_transform(X)

array([[0.   , 1.   , 0.04 ],
       [1.   , 0.   , 0.001],
       [0.6  , 0.   , 0.7  ],
       [0.2  , 0.   , 0.4  ],
       [0.8  , 0.5  , 1.   ]])

- TransformerMixin
    - fit_transform enabled
    - Can use our SpecialTransformer in other sklearn transformer functionality (will see later):
        - Column Transformers
        - Feature Unions
        - etc

- BaseEsimator
    - can use in rest of sklearn framework
    - Other sklearn classes can access externally controlled variables in a model's constructor

Let's change the code so that:

- If the value is greater than a *threshold*, scale value by the **largest value** in that column
- If the value is smaller than *threshold*, change it to $0$

In [110]:
class SpecialTransformer(BaseEstimator, TransformerMixin):
    
    def __init__(self, threshold = 0):
        self.max_ = None
        self.threshold = threshold
        BaseEstimator.__init__(self)
        TransformerMixin.__init__(self)
    
    def fit(self, X, y=None):
        self.max_ = np.max(X,axis=0) 
        return self
    
    def transform(self, X):
        X_copy = np.copy(X)
        X_copy[X_copy < self.threshold] = 0
        return X_copy / self.max_

Base estimator has:
- .get_params()
- .set_params()

In [111]:
trans_instance2 = SpecialTransformer(threshold = 10)
trans_instance2.fit(X)

SpecialTransformer(threshold=10)

Other sklearn classes may need to check argument of constructor:
- get_params()

Returns a dict

In [112]:
trans_instance2.get_params()

{'threshold': 10}

Other sklearn classes may need to directly access and manipulate model constructors:
- will see this in model tuning 

In [117]:
dict_hyperparams = {'threshold': 200}
trans_instance2.set_params(**dict_hyperparams)

SpecialTransformer(threshold=200)

In [115]:
trans_instance2

SpecialTransformer(threshold=200)